services:

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  patient-db:
    image: postgres:16
    container_name: patient-db
    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - patient-db-data:/var/lib/postgresql/data

  document-db:
    image: postgres:16
    container_name: document-db
    environment:
      POSTGRES_DB: document_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - document-db-data:/var/lib/postgresql/data


volumes:
  auth-db-data:
  patient-db-data:
  document-db-data: