apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres

spec:
  containers:
    - name: postgres
      image: postgres:16

      env:
        - name: POSTGRES_USER
          value: postgres

        - name: POSTGRES_PASSWORD
          value: postgres

        - name: POSTGRES_DB
          value: auth_db

      ports:
        - containerPort: 5432